### PR TITLE
[RFR]Fix some resources limitations

### PR DESCRIPTION
**Pull request by shalomnaim1**
* Fix Kafka memory limitations due to OOMKilled on Kafka's pod
* Change the size of DB's PVC to 10GiB due to OSD quota

### CODE REVIEW

**Comment by shalomnaim1** [comment]
@carbonin Could you take a look at this PR please????

Thanks :+1:

**Comment by gmcculloug** [comment]
cc @bzwei

**Comment by carbonin** [comment]
@shalomnaim1 why are you deploying kafka in the insights environment? You should be using the provided messaging service.

**Comment by zsadeh** [comment]
@carbonin We followed the steps in the readme.md. How do we get the provided messaging service instead?

**Comment by carbonin** [comment]
@zsadeh It's in the readme :smile: 

https://github.com/ManageIQ/approval-deploy#deploy-from-buildfactory-with-an-external-queue-service-and-a-path-prefix

**Comment by carbonin** [comment]
Also I would think this is how the other projects are deployed already, right @shalomnaim1 ?

**Comment by zsadeh** [comment]
@carbonin How could we get to use the external Kafka service in OSD?

**Comment by zsadeh** [comment]
@carbonin in the readme I found the following params:
QUEUE_HOST=platform-mq-ci-kafka-bootstrap.platform-mq-ci.svc
PATH_PREFIX=r/insights/platform
RBAC_HOST=rbac.rbac-ci.svc.cluster.local

Should I change anything or use them as is? Reminder - I am working approval-qa namespace.
If the parameters need a change, I think it is worth to mention this in the readme.me

**Comment by carbonin** [comment]
@zsadeh I'm not going to enumerate every possible external queue host in the readme. The expectation is that you know what queue you should be pointing to based on what you're trying to accomplish.

That said, I also don't understand the issue with the PVC, is the approval-qa quota value for storage lower than the other projects (catalog, topological-inventory)? That wasn't a problem in either of those...

**Comment by carbonin** [comment]
Closing this as the issue was resolved in the cluster.

**Pull request closed without merging**
